[profile.default]
src = 'contracts'
out = 'out'
libs = ['lib']
remappings = [
    "@openzeppelin/=lib/openzeppelin-contracts/",
    "@aave/=lib/aave/",
    "@foundry/=lib/foundry/",
    "@ds-test/=lib/forge-std/lib/ds-test/src/",
    "@forge-std/=lib/forge-std/src/"
]
